import React from 'react'
import Image from 'next/image'

const AfterPhone = () => {
  return (
    <div className="relative">
      {/* Phone Card */}
      <div className="w-80 h-96 bg-blue-900 rounded-3xl shadow-lg border border-gray-100 p-2 relative overflow-hidden">        
        {/* Inner bordered screen */}
        <div className="w-full h-full bg-white rounded-2xl border border-gray-200 shadow-inner p-3 flex flex-col">
          {/* Header */}
          <div className="flex items-center gap-2 mb-3">
            <div className="w-7 h-7 bg-gray-300 rounded-full flex items-center justify-center text-gray-600 text-[10px] font-bold">🤖</div>
            <div>
              <div className="text-sm font-semibold text-gray-800">SatyaShield WhatsApp Bot</div>
              <div className="text-[10px] text-gray-500 -mt-0.5">online</div>
            </div>
          </div>

          {/* User message bubble */}
          <div className="flex justify-end mb-3">
            <div className="max-w-[75%] bg-blue-400 text-white text-sm px-3 py-2 rounded-2xl rounded-br-sm shadow">
              Is this real ???
            </div>
          </div>

          {/* Fact check card */}
          <div className="bg-gray-50 rounded-xl border border-gray-200 overflow-hidden">
            {/* Preview row */}
            <div className="flex items-center gap-2 p-2 border-b border-gray-200 bg-gray-100">
              <div className="relative w-14 h-10 rounded-md overflow-hidden">
                <Image src="/icons/bidengun.png" alt="Preview" fill className="object-cover" />
              </div>
              <div className="text-[11px] text-gray-700">Image shows Joe Biden holding a disassembled handgun</div>
            </div>

            {/* Content */}
            <div className="p-3 text-[12px] leading-5 text-gray-800 space-y-2">
              <div><span className="font-semibold">📌 Claim :</span> The image shows Joe Biden holding a disassembled handgun and claiming that he was present at the Mar-a-Lago FBI raid as an agent.</div>
              <div><span className="font-semibold">✅ Verdict :</span> False</div>
              <div><span className="font-semibold">📊 Confidence :</span> 100%</div>
              <div><span className="font-semibold">💬 Explanation :</span> The image was generated by AI; known datasets showcase a synthetic image of 'Biden holding a firearm', which explains the realism issues.</div>
              <div>
                <span className="font-semibold">📚 Sources :</span>
                <div className="text-blue-600 truncate">https://edition.cnn.com/2023/06/21/politics/fact-check-biden-guns-africa</div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

export default AfterPhone